### ISSUE TITLE
500PX error response: status code = 401 when favourite post

### ISSUE THREAD

**Issue by rhawidantas** [akirahrkw/python-500px#6]
I am having some trouble with the favourite post:
...OAuthHandler - set_request_token - xauth set_access_token and so on

```
for s in popular['photos']:
    photo_id = s['id']
    api.photos_favorite_post(id=photo_id)
```

So right after the first loop I get the error: 500PX error response: status code = 401

I tried re setting the access token by handler.set_access_token(xauth_token.key,  xauth_token.secret)
 but no avail.

Any ideas?

**Comment by rhawidantas** [comment]
Upon further inspection I found out that test case for photo favourites are not passing. I went to the 500px page to check which endpoints are available and seems that favourite has been removed from it can you confirm?

Which makes it even more strange since when using the console (https://apigee.com/vova/embed/console/api500px) it is possible to make a post to that endpoint. 

Any ideas?

**Comment by vovko** [comment]
@akirahrkw @rhawidantas can confirm, favorite and vote actions are getting 401 even though requests are signed. Tried both Oauth and Xauth, all authed post actions work except Vote and Favorite

**Comment by akirahrkw** [comment]
@vovko @rhawidantas  thanks for letting me know, somehow I was missing this issue... let me check soon.

**Comment by akirahrkw** [comment]
@vovko @rhawidantas  sorry for late reply, yes the test case is not working properly. I will fix soon.

**Comment by vovko** [comment]
@akirahrkw great, thank you!

**Comment by akirahrkw** [comment]
@vovko @rhawidantas 
just pushed v0.3(latest master branch)
https://github.com/akirahrkw/python-500px/tree/0.3

I think there were some minor changes on the API (how to pass parameters) before.

**Comment by vovko** [comment]
@akirahrkw thank you so much for fixing this! 🙏  💯  :1st_place_medal:
